[workspace]
authors = ["Thibault Schowing <th.schow@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "PBI"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pandas = ">=2.3.1,<3"
snakemake = ">=7.32.4,<10"
ydata-profiling = ">=4.16.0,<5"
numpy = ">=2.1.3,<3"
mamba = ">=2.3.1,<3"

[feature.reporting.dependencies]
python = ">=3.7,<3.11"
ydata-profiling = "*"
pandas = "*"
numpy = "*"
matplotlib = "*"

[feature.base.dependencies]
python = "*"
pandas = "*"
numpy = "*"
matplotlib = "*"
snakemake = "*"
mamba = "*"

[environments]
reporting = ["reporting"]
base = ["base"]
